/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.util.Vector;

/**
 *
 * @author Martin
 */
public class AltaCompetencia extends javax.swing.JPanel {
    
    TablaDisponibilidad tablaDisp = new TablaDisponibilidad();
    
    /**
     * Creates new form AltaCompetencia
     */
    public AltaCompetencia() {
        initComponents();
    }
    
    //private Vector< Vector<Object> > tabla;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        DeporteAsociado = new javax.swing.JComboBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        nombreComp = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jComboBox3 = new javax.swing.JComboBox();
        ACEPTAR = new javax.swing.JButton();
        ATRAS = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(null);

        tablaDisp=new TablaDisponibilidad();
        jPanel1.add(tablaDisp);
        jPanel1.setToolTipText("");
        jPanel1.setMinimumSize(new java.awt.Dimension(100, 100));
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 260));
        add(jPanel1);
        jPanel1.setBounds(50, 230, 300, 260);
        revalidate();
        repaint();

        jLabel7.setText("Puntos por presentarse:");
        add(jLabel7);
        jLabel7.setBounds(500, 280, 160, 14);

        jLabel2.setText("NOMBRE DE COMPETENCIA");
        add(jLabel2);
        jLabel2.setBounds(40, 80, 180, 14);

        String[] cadena2= new String[] { "Puntuacion", "Sets", "Resultado Final" };
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(cadena2));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        add(jComboBox1);
        jComboBox1.setBounds(500, 130, 190, 20);
        if((String)jComboBox1.getSelectedItem()=="Puntuacion"){formaPPuntuacion();}
        else if((String)jComboBox1.getSelectedItem()=="Sets"){formaPSets();}
        else formaPResultadoFinal();

        String[] cadena= new String[] { "Liga", "Eliminacion Simple", "Eliminacion Doble" };
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(cadena));
        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });
        add(jComboBox2);
        jComboBox2.setBounds(500, 170, 190, 20);
        if((String)jComboBox2.getSelectedItem()=="Liga"){modalidadLiga();}
        else modalidadEliminatoria();

        DeporteAsociado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Futbol", "Basquet", "Voley" }));
        DeporteAsociado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeporteAsociadoActionPerformed(evt);
            }
        });
        add(DeporteAsociado);
        DeporteAsociado.setBounds(50, 130, 138, 20);

        jCheckBox5.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBox5StateChanged(evt);
            }
        });
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });
        add(jCheckBox5);
        jCheckBox5.setBounds(680, 310, 20, 20);

        nombreComp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreCompActionPerformed(evt);
            }
        });
        add(nombreComp);
        nombreComp.setBounds(50, 100, 220, 20);

        jLabel3.setText("Lugar:");
        add(jLabel3);
        jLabel3.setBounds(50, 160, 50, 14);

        jLabel4.setText("Cant:");
        add(jLabel4);
        jLabel4.setBounds(210, 160, 30, 14);

        jButton1.setText("LISTAR PARTICPANTE DE COMPETENCIA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(305, 508, 231, 23);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        add(jComboBox3);
        jComboBox3.setBounds(90, 180, 102, 20);

        ACEPTAR.setText("DAR DE ALTA");
        ACEPTAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACEPTARActionPerformed(evt);
            }
        });
        add(ACEPTAR);
        ACEPTAR.setBounds(554, 508, 114, 23);

        ATRAS.setText("ATRAS");
        ATRAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ATRASActionPerformed(evt);
            }
        });
        add(ATRAS);
        ATRAS.setBounds(69, 508, 90, 23);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Dar de Alta Competencia Deportiva");
        add(jLabel1);
        jLabel1.setBounds(220, 10, 350, 50);

        jLabel5.setText("Reglamento (opcional):");
        add(jLabel5);
        jLabel5.setBounds(370, 360, 150, 14);

        jLabel8.setText("Puntos por empate:");
        add(jLabel8);
        jLabel8.setBounds(500, 340, 150, 14);

        jLabel9.setText("Puntos por partidos ganados:");
        add(jLabel9);
        jLabel9.setBounds(500, 250, 160, 14);

        jLabel10.setText("Permite empate?");
        add(jLabel10);
        jLabel10.setBounds(500, 310, 130, 14);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        add(jTextField1);
        jTextField1.setBounds(670, 220, 40, 20);

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        add(jTextField4);
        jTextField4.setBounds(670, 340, 40, 20);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        add(jTextField2);
        jTextField2.setBounds(670, 280, 40, 20);

        jLabel11.setText("Tantos por no presentarse");
        add(jLabel11);
        jLabel11.setBounds(500, 220, 160, 14);

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        add(jTextField5);
        jTextField5.setBounds(670, 250, 40, 20);

        jFormattedTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField1ActionPerformed(evt);
            }
        });
        add(jFormattedTextField1);
        jFormattedTextField1.setBounds(240, 180, 40, 20);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        add(jScrollPane2);
        jScrollPane2.setBounds(370, 380, 340, 96);

        jButton3.setText("+");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3);
        jButton3.setBounds(300, 180, 50, 23);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ventanas/img_general.jpg"))); // NOI18N
        add(jLabel6);
        jLabel6.setBounds(0, 0, 800, 600);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void DeporteAsociadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeporteAsociadoActionPerformed

    }//GEN-LAST:event_DeporteAsociadoActionPerformed

    private void nombreCompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreCompActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreCompActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void ACEPTARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACEPTARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ACEPTARActionPerformed

    private void ATRASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ATRASActionPerformed
        V.get().menu();
    }//GEN-LAST:event_ATRASActionPerformed

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
        if((String)jComboBox2.getSelectedItem()=="Liga"){modalidadLiga();}
        else modalidadEliminatoria();
    }//GEN-LAST:event_jComboBox2ItemStateChanged

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        if((String)jComboBox1.getSelectedItem()=="Puntuacion"){formaPPuntuacion();}
        else if((String)jComboBox1.getSelectedItem()=="Sets"){formaPSets();}
        else formaPResultadoFinal();
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jCheckBox5StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBox5StateChanged
        if(jCheckBox5.isSelected()){
            jLabel8.setVisible(true);
            jTextField4.setVisible(true);
        }
        else {
            jLabel8.setVisible(false);
            jTextField4.setVisible(false);
        }
    }//GEN-LAST:event_jCheckBox5StateChanged

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jFormattedTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int a= Integer.parseInt(jFormattedTextField1.getText());
        if(a>0){
            agregarATabla((String)jComboBox3.getSelectedItem(),a);
        }
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ACEPTAR;
    private javax.swing.JButton ATRAS;
    private javax.swing.JComboBox DeporteAsociado;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField nombreComp;
    // End of variables declaration//GEN-END:variables
    
    
    //(Des)habilitacion de botones dependiendo de los comboBox
    
    //Habilitacion de campos para la modalidad de liga
    private void modalidadLiga(){
        
        //jTextField4.setVisible(true);
        jTextField5.setVisible(true);
        jTextField2.setVisible(true);
        jCheckBox5.setVisible(true);
        jLabel7.setVisible(true);
        //jLabel8.setVisible(true);
        jLabel9.setVisible(true);
        jLabel10.setVisible(true);
        verEmpate();
    }
    
    //Habilitacion de campos para modalidad de eliminatorias
    private void modalidadEliminatoria(){
        
        jTextField4.setVisible(false);
        jTextField5.setVisible(false);
        jTextField2.setVisible(false);
        jCheckBox5.setVisible(false);
        jLabel7.setVisible(false);
        jLabel8.setVisible(false);
        jLabel9.setVisible(false);
        jLabel10.setVisible(false);
        
        // modificar jlabel 11
    }
    
    //Habilitacion de campos para forma de puntuacion, puntuacion
    private void formaPPuntuacion(){
        jLabel11.setVisible(true);
        jTextField1.setVisible(true);
        jLabel11.setText("Tantos por no presentarse");
    }
    //Habilitacion de campos para forma de puntuacion, sets
    private void formaPSets(){
        jLabel11.setVisible(true);
        jTextField1.setVisible(true);
        jLabel11.setText("Cant. max. de sets");
    }
    //Habilitacion de campos para forma de puntuacion, Resultado final
    private void formaPResultadoFinal(){
        jLabel11.setVisible(false);
        jTextField1.setVisible(false);
    }
    
    //Verificacion del campo para ingresar tantos por empate
    private void verEmpate(){
        verCheckBoxEmpate();
    }
    private void verCheckBoxEmpate(){
        if(jCheckBox5.isSelected()){
            jLabel8.setVisible(true);
            jTextField4.setVisible(true);
        }
        else {
            jLabel8.setVisible(false);
            jTextField4.setVisible(false);
        }
    }
    
    
    private void agregarATabla(String lugar, int cantidad){
        tablaDisp.addFila(lugar, cantidad);
        /*Vector<Object> auxLocal= new Vector<>();
        auxLocal.add(lugar);
        auxLocal.add(cantidad);
        auxLocal.add("BOTON");*/
        //tabla.add(auxLocal);
    }
    
}
