/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.awt.event.ActionEvent;
import javax.swing.JPanel;

/**
 *
 * @author Martin
 */
public class V extends javax.swing.JFrame {
   
    // Forma de SINGLETON
    private static V SELF = new V();
    //private V() {}
    public static V get(){
        return SELF;
    }
    
    /**
     * Creates new form VentanaPrincipal
     */
    private V() {
        initComponents();
    }
    
    private JPanel aux;
    
    public void limpiar(){
        //SELF.removeAll(); NOOOO, elimina nose que masss
        remove(aux);
    }
    
    public void menu(){
        limpiar();
        aux = new Menu();
        add(aux);
        revalidate();
        repaint();
    }
    
    public void listarCD(){
        limpiar();
        aux=new ListarCompetencias();
        add(aux);
        revalidate();
        repaint();
    }
    
    public void altaCompetencia(){
        limpiar();
        aux = new AltaCompetencia();
        add(aux);
        revalidate();
        repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 630));
        setPreferredSize(new java.awt.Dimension(800, 630));
        setResizable(false);
        setLocationRelativeTo(null);
        
        aux=new Bienvenido();
        aux.setVisible(true);
        add(aux);
        /*javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(aux)
        ));
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(aux)
        ));
        
        /*getContentPane().add(aux);
        aux.setVisible(true);*/
        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new V().get().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    
    // End of variables declaration                   
}
